apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: greeting
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        enabled: true
        paths:
          - /var/log/app/*.log
        json.keys_under_root: true
        json.add_error_key: true
        json.message_key: msg
        fields:
          app: greeting-api
          environment: kubernetes
        fields_under_root: true

    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
      index: "greeting-api-%{+yyyy.MM.dd}"

    setup.template.name: "greeting-api"
    setup.template.pattern: "greeting-api-*"
    setup.ilm.enabled: false

    logging.level: info
    logging.to_files: false
