apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: greeting

resources:
  - namespace.yaml
  - elasticsearch.yaml
  - kibana.yaml
  - greeting-api.yaml

configMapGenerator:
  - name: filebeat-config
    files:
      - filebeat.yml
    options:
      disableNameSuffixHash: true
